Workaround System.TypeLoad exception when running test-suite on macOS.
It was reproducible while running Compile.sh on macOS:

mono64 --debug "../lib/Release_x64/Encodings.Gen.exe"

Generating bindings for Encodings (CSharp)
Looking for tests in: /Users/joao/Dev/CppSharp/tests/Encodings
Parsed 'Encodings.h'

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'CppSharp.MSVCToolchain:<>f__am$cache7' (8) due to: Could not load file or assembly 'Microsoft.VisualStudio.Setup.Configuration.Interop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.