Workaround VS 2015 support since Clang cannot handle it yet.
Errors:

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(227,22): error: use of undeclared identifier 'char16_t'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(233,22): error: use of undeclared identifier 'char32_t'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(408,14):error: use of undeclared identifier 'char16_t'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(414,14):error: use of undeclared identifier 'char32_t'
C:\Program Files (x86)\Windows Kits\8.1\include\um\winnt.h(938,2): error: Must define a target architecture.
C:\Program Files (x86)\Windows Kits\8.1\include\um\oaidl.h(473,31): error: cannot combine with previous 'type-name' declaration specifier